version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_TYPE: mysql
      DB_HOST: db
      DB_NAME: produits
      DB_USER: root
      DB_PASS: root
    networks:
      - produits

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: produits
    networks:
      - produits

networks:
  produits:
